name: redis
version: 1.4.0
description: Redis database (https://redis.io/) client, with both simplicity and performance as primary goals.
homepage: https://github.com/ra1u/redis-dart
repository: https://github.com/ra1u/redis-dart
issue_tracker: https://github.com/ra1u/redis-dart/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.6.5
